const acceptHeaders = [
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
  "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,en-US;q=0.5',
  'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,en;q=0.7',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/atom+xml;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/rss+xml;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/json;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/ld+json;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/xml-dtd;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/xml-external-parsed-entity;q=0.9',
  'text/html; charset=utf-8',
  'application/json, text/plain, */*',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,text/xml;q=0.9',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,text/plain;q=0.8',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    '*/*',
    'image/*',
    'image/webp,image/apng',
    'text/html',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
    ]; 
 
const langHeaders = [
 'ko-KR',
 'en-US',
 'zh-CN',
 'zh-TW',
 'ja-JP',
 'en-GB',
 'en-AU',
 'en-GB,en-US;q=0.9,en;q=0.8',
 'en-GB,en;q=0.5',
 'en-CA',
 'en-UK, en, de;q=0.5',
 'en-NZ',
 'en-GB,en;q=0.6',
 'en-ZA',
 'en-IN',
 'en-PH',
 'en-SG',
 'en-HK',
 'en-GB,en;q=0.8',
 'en-GB,en;q=0.9',
 ' en-GB,en;q=0.7',
 '*',
 'en-US,en;q=0.5',
 'vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5',
 'utf-8, iso-8859-1;q=0.5, *;q=0.1',
 'fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5',
 'en-GB, en-US, en;q=0.9',
 'de-AT, de-DE;q=0.9, en;q=0.5',
 'cs;q=0.5',
 'da, en-gb;q=0.8, en;q=0.7',
 'he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7',
 'en-US,en;q=0.9',
 'de-CH;q=0.7',
 'tr',
 'zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2'
 ];

const refers = [
 "https://www.google.com/search?q=",
 "https://check-host.net/",
 "https://www.facebook.com/",
 "https://www.youtube.com/",
 "https://www.fbi.com/",
 "https://www.bing.com/search?q=",
 "https://r.search.yahoo.com/",
 "https://www.cia.gov/index.html",
 "https://vk.com/profile.php?redirect=",
 "https://www.usatoday.com/search/results?q=",
 "https://help.baidu.com/searchResult?keywords=",
 "https://steamcommunity.com/market/search?q=",
 "https://www.ted.com/search?q=",
 "https://play.google.com/store/search?q=",
 "https://www.qwant.com/search?q=",
 "https://soda.demo.socrata.com/resource/4tka-6guv.json?$q=",
 "https://www.google.ad/search?q=",
 "https://www.google.ae/search?q=",
 "https://www.google.com.af/search?q=",
 "https://www.google.com.ag/search?q=",
 "https://www.google.com.ai/search?q=",
 "https://www.google.al/search?q=",
 "https://www.google.am/search?q=",
 "https://www.google.co.ao/search?q=",
 "http://anonymouse.org/cgi-bin/anon-www.cgi/",
 "http://coccoc.com/search#query=",
 "http://ddosvn.somee.com/f5.php?v=",
 "http://engadget.search.aol.com/search?q=",
 "http://engadget.search.aol.com/search?q=query?=query=&q=",
 "http://eu.battle.net/wow/en/search?q=",
 "http://filehippo.com/search?q=",
 "http://funnymama.com/search?q=",
 "http://go.mail.ru/search?gay.ru.query=1&q=?abc.r&q=",
 "http://go.mail.ru/search?gay.ru.query=1&q=?abc.r/",
 "http://go.mail.ru/search?mail.ru=1&q=",
 "http://help.baidu.com/searchResult?keywords=",
 "http://host-tracker.com/check_page/?furl=",
 "http://itch.io/search?q=",
 "http://jigsaw.w3.org/css-validator/validator?uri=",
 "http://jobs.bloomberg.com/search?q=",
 "http://jobs.leidos.com/search?q=",
 "http://jobs.rbs.com/jobs/search?q=",
 "http://king-hrdevil.rhcloud.com/f5ddos3.html?v=",
 "http://louis-ddosvn.rhcloud.com/f5.html?v=",
 "http://millercenter.org/search?q=",
 "http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0&q=",
 "http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0/",
 "http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B&q=",
 "http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B/",
 "http://page-xirusteam.rhcloud.com/f5ddos3.html?v=",
 "http://php-hrdevil.rhcloud.com/f5ddos3.html?v=",
 "http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x&q=",
 "http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x/",
 "http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf&q=",
 "http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf/",
 "http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%&q=",
 "http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%/",
 "http://search.aol.com/aol/search?q=",
 "http://taginfo.openstreetmap.org/search?q=",
 "http://techtv.mit.edu/search?q=",
 "http://validator.w3.org/feed/check.cgi?url=",
 "http://vk.com/profile.php?redirect=",
 "http://www.ask.com/web?q=",
 "http://www.baoxaydung.com.vn/news/vn/search&q=",
 "http://www.bestbuytheater.com/events/search?q=",
 "http://www.bing.com/search?q=",
 "http://www.evidence.nhs.uk/search?q=",
 "http://www.google.com/?q=",
 "http://www.google.com/translate?u=",
 "http://www.google.ru/url?sa=t&rct=?j&q=&e&q=",
 "http://www.google.ru/url?sa=t&rct=?j&q=&e/",
 "http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=",
 "http://www.pagescoring.com/website-speed-test/?url=",
 "http://www.reddit.com/search?q=",
 "http://www.search.com/search?q=",
 "http://www.shodanhq.com/search?q=",
 "http://www.ted.com/search?q=",
 "http://www.topsiteminecraft.com/site/pinterest.com/search?q=",
 "http://www.usatoday.com/search/results?q=",
 "http://www.ustream.tv/search?q=",
 "http://yandex.ru/yandsearch?text=",
 "http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81%&q=",
 "http://ytmnd.com/search?q=",
 "https://add.my.yahoo.com/rss?url=",
 "https://careers.carolinashealthcare.org/search?q=",
 "https://check-host.net/",
 "https://developers.google.com/speed/pagespeed/insights/?url=",
 "https://drive.google.com/viewerng/viewer?url=",
 "https://duckduckgo.com/?q=",
 "https://google.com/",
 "https://google.com/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=&q=",
 "https://google.com/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882&q=",
 "https://help.baidu.com/searchResult?keywords=",
 "https://play.google.com/store/search?q=",
 "https://pornhub.com/",
 "https://r.search.yahoo.com/",
 "https://soda.demo.socrata.com/resource/4tka-6guv.json?$q=",
 "https://steamcommunity.com/market/search?q=",
 "https://vk.com/profile.php?redirect=",
 "https://www.bing.com/search?q=",
 "https://www.cia.gov/index.html",
 "https://www.facebook.com/",
 "https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=",
 "https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=",
 "https://www.fbi.com/",
 "https://www.google.ad/search?q=",
 "https://www.google.ae/search?q=",
 "https://www.google.al/search?q=",
 "https://www.google.co.ao/search?q=",
 "https://www.google.com.af/search?q=",
 "https://www.google.com.ag/search?q=",
 "https://www.google.com.ai/search?q=",
 "https://www.google.com/search?q=",
 "https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832&q=",
 "https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925&q=",
 "https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882&q=",
 "https://www.npmjs.com/search?q=",
 "https://www.om.nl/vaste-onderdelen/zoeken/?zoeken_term=",
 "https://www.pinterest.com/search/?q=",
 "https://www.qwant.com/search?q=",
 "https://www.ted.com/search?q=",
 "https://www.usatoday.com/search/results?q=",
 "https://www.yandex.com/yandsearch?text=",
 "https://www.youtube.com/",
 "https://yandex.ru/",
   'http://anonymouse.org/cgi-bin/anon-www.cgi/',
   'http://coccoc.com/search#query=',
   'http://ddosvn.somee.com/f5.php?v=',
   'http://engadget.search.aol.com/search?q=',
   'http://engadget.search.aol.com/search?q=query?=query=&q=',
   'http://eu.battle.net/wow/en/search?q=',
   'http://filehippo.com/search?q=',
   'http://funnymama.com/search?q=',
   'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r&q=',
   'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r/',
   'http://go.mail.ru/search?mail.ru=1&q=',
   'http://help.baidu.com/searchResult?keywords=',
   'http://host-tracker.com/check_page/?furl=',
   'http://itch.io/search?q=',
   'http://jigsaw.w3.org/css-validator/validator?uri=',
   'http://jobs.bloomberg.com/search?q=',
   'http://jobs.leidos.com/search?q=',
   'http://jobs.rbs.com/jobs/search?q=',
   'http://king-hrdevil.rhcloud.com/f5ddos3.html?v=',
   'http://louis-ddosvn.rhcloud.com/f5.html?v=',
   'http://millercenter.org/search?q=',
   'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0&q=',
   'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0/',
   'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B&q=',
   'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B/',
   'http://page-xirusteam.rhcloud.com/f5ddos3.html?v=',
   'http://php-hrdevil.rhcloud.com/f5ddos3.html?v=',
   'http://ru.search.yahoo.com/search?_query?=l%t=?=?A7x&q=',
   'http://ru.search.yahoo.com/search?_query?=l%t=?=?A7x/',
   'http://ru.search.yahoo.com/search_yzt=?=A7x9Q.bs67zf&q=',
   'http://ru.search.yahoo.com/search_yzt=?=A7x9Q.bs67zf/',
   'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%&q=',
   'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%/',
   'http://search.aol.com/aol/search?q=',
   'http://taginfo.openstreetmap.org/search?q=',
   'http://techtv.mit.edu/search?q=',
   'http://validator.w3.org/feed/check.cgi?url=',
   'http://vk.com/profile.php?redirect=',
   'http://www.ask.com/web?q=',
   'http://www.baoxaydung.com.vn/news/vn/search&q=',
   'http://www.bestbuytheater.com/events/search?q=',
   'http://www.bing.com/search?q=',
   'http://www.evidence.nhs.uk/search?q=',
   'http://www.google.com/?q=',
   'http://www.google.com/translate?u=',
   'http://www.google.ru/url?sa=t&rct=?j&q=&e&q=',
   'http://www.google.ru/url?sa=t&rct=?j&q=&e/',
   'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=',
   'http://www.pagescoring.com/website-speed-test/?url=',
   'http://www.reddit.com/search?q=',
   'http://www.search.com/search?q=',
   'http://www.shodanhq.com/search?q=',
   'http://www.ted.com/search?q=',
   'http://www.topsiteminecraft.com/site/pinterest.com/search?q=',
   'http://www.usatoday.com/search/results?q=',
   'http://www.ustream.tv/search?q=',
   'http://yandex.ru/yandsearch?text=',
   'http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81%&q=',
   'http://ytmnd.com/search?q=',
   'https://add.my.yahoo.com/rss?url=',
   'https://careers.carolinashealthcare.org/search?q=',
   'https://check-host.net/',
   'https://developers.google.com/speed/pagespeed/insights/?url=',
   'https://drive.google.com/viewerng/viewer?url=',
   'https://duckduckgo.com/?q=',
   'https://google.com/',
   'https://google.com/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=&q=',
   'https://google.com/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882&q=',
   'https://help.baidu.com/searchResult?keywords=',
   'https://play.google.com/store/search?q=',
   'https://pornhub.com/',
   'https://r.search.yahoo.com/',
   'https://soda.demo.socrata.com/resource/4tka-6guv.json?$q=',
   'https://steamcommunity.com/market/search?q=',
   'https://vk.com/profile.php?redirect=',
   'https://www.bing.com/search?q=',
   'https://www.cia.gov/index.html',
   'https://www.facebook.com/',
   'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
   'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
   'https://www.fbi.com/',
   'https://www.google.ad/search?q=',
   'https://www.google.ae/search?q=',
   'https://www.google.al/search?q=',
   'https://www.google.co.ao/search?q=',
   'https://www.google.com.af/search?q=',
   'https://www.google.com.ag/search?q=',
   'https://www.google.com.ai/search?q=',
   'https://www.google.com/search?q=',
   'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832&q=',
   'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925&q=',
   'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882&q=',
   'https://www.npmjs.com/search?q=',
   'https://www.om.nl/vaste-onderdelen/zoeken/?zoeken_term=',
   'https://www.pinterest.com/search/?q=',
   'https://www.qwant.com/search?q=',
   'https://www.ted.com/search?q=',
   'https://www.usatoday.com/search/results?q=',
   'https://www.yandex.com/yandsearch?text=',
   'https://www.youtube.com/',
   'https://yandex.ru/',
   'https://www.betvictor106.com/?jskey=BBOR1oulRNQaihu%2BdyW7xFyxxf0sxIMH%2BB%2FKe4qvs6S3u89h1BcavwQ%3D'
   ];
   
   
const controle_header = [
 'max-age=604800',
 'proxy-revalidate',
 'public, max-age=0',
 'max-age=315360000',
 'public, max-age=86400, stale-while-revalidate=604800, stale-if-error=604800',
 's-maxage=604800',
 'max-stale',
 'public, immutable, max-age=31536000',
 'must-revalidate',
 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
 'max-age=31536000,public,immutable',
 'max-age=31536000,public',
 'min-fresh',
 'private',
 'public',
 's-maxage',
 'no-cache',
 'no-cache, no-transform',
 'max-age=2592000',
 'no-store',
 'no-transform',
 'max-age=31557600',
 'stale-if-error',
 'only-if-cached',
 'max-age=0',
 'must-understand, no-store',
 'max-age=31536000; includeSubDomains',
 'max-age=31536000; includeSubDomains; preload',
 'max-age=120',
 'max-age=0,no-cache,no-store,must-revalidate',
 'public, max-age=604800, immutable',
 'max-age=0, must-revalidate, private',
 'max-age=0, private, must-revalidate',
 'max-age=604800, stale-while-revalidate=86400',
 'max-stale=3600',
 'public, max-age=2678400',
 'min-fresh=600',
 'public, max-age=30672000',
 'max-age=31536000, immutable',
 'max-age=604800, stale-if-error=86400',
 'public, max-age=604800',
 'no-cache, no-store,private, max-age=0, must-revalidate',
 'o-cache, no-store, must-revalidate, pre-check=0, post-check=0',
 'public, s-maxage=600, max-age=60',
 'public, max-age=31536000',
 'max-age=14400, public',
 'max-age=14400',
 'max-age=600, private',
 'public, s-maxage=600, max-age=60',
 'no-store, no-cache, must-revalidate',
 'no-cache, no-store,private, s-maxage=604800, must-revalidate',
 'Sec-CH-UA,Sec-CH-UA-Arch,Sec-CH-UA-Bitness,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Mobile,Sec-CH-UA-Model,Sec-CH-UA-Platform,Sec-CH-UA-Platform-Version,Sec-CH-UA-WoW64',
];
   
   
function randomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

module.exports = {
  accept: { "Accept": randomElement(acceptHeaders) },
  lang: randomElement(langHeaders),
  randomReferer: randomElement(referers),
  CacheControl: randomElement(controle_header)
};